#!/usr/bin/bash
##
## yhOS
## Copyright (c) aceinet
## License: GPL-2.0
##
set -e

echo "Makefile generator for yhOS"

if [ -f Makefile ]; then
	rm Makefile
fi

if [ ! -f .Makefile ]; then
	echo "Makefile template does not exist. Cannot continue"
	exit
fi

# check if kernel/rom.h exists, then the kernel can use it checking for ROM_EXISTS definition
cflags="CFLAGS = -I. -Werror -Wall -Wextra -DGIT_COMMIT='\"\$(GIT_COMMIT)\"' -DVFS_SIZE=4096"
romfile=""
makegen_deps=""
if [ ! -f kernel/rom.h ]; then
	cflags="${cflags}"
else
	cflags="${cflags} -DROM_EXISTS"
	romfile="kernel/rom.h"
fi

if which dcc >/dev/null; then
	echo "DC compiler detected, going to use it"
	cflags="${cflags} -DDCC_EXISTS"
	makegen_deps="${makegen_deps} build/dc_test.o"
else
	echo "DC compiler not detected"
fi

echo ${cflags} >> Makefile
echo "ROMFILE = ${romfile}" >> Makefile
echo "MAKEGEN_DEPS =${makegen_deps}" >> Makefile
cat .Makefile >> Makefile

if which dcc >/dev/null; then
	echo "" >> Makefile
	echo "build/dc_test.o: build/dc_test.ll" >> Makefile
	echo "	\$(dir_guard)" >> Makefile
	echo "	\$(DCC_COLOR)" >> Makefile
	echo "	llc build/dc_test.ll -o build/dc_test.o -march=x86 -filetype=obj" >> Makefile
	echo "	\$(RESET_COLOR)" >> Makefile
	echo "" >> Makefile
	echo "build/dc_test.ll: kernel/dc_test.dc" >> Makefile
	echo "	\$(dir_guard)" >> Makefile
	echo "	\$(DCC_COLOR)" >> Makefile
	echo "	dcc kernel/dc_test.dc -i -o build/dc_test --nostdlib" >> Makefile
	echo "	\$(RESET_COLOR)" >> Makefile
fi

echo "Generated successfully"
