#!/usr/bin/python3
import os, sys, subprocess

def main():
	script_path = os.path.dirname(__file__)

	subprocess.run(["i386-elf-g++", *sys.argv[1:], "-ffreestanding", "-m32", f"-I{script_path}/include", f"-I{script_path}/.."])

if __name__ == '__main__':
	main()
