#!/usr/bin/bash
##
## yhOS
## Copyright (c) aceinet
## License: GPL-2.0
##
echo "i386-yhse-gcc: toolchain by aceinet for yhOS"
dir=$(dirname -- "$0")
i386-elf-gcc $@ -ffreestanding -m32 -nostdlib -m32
